In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [3]:
## Load the dataset
data=pd.read_csv('Churn_Modelling.csv')
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [4]:
## Preprocess Data
## Drop unnecessary columns
data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

      RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [6]:
## Encoding categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data

      RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary  Exited
0             1    15634602   Hargrave  ...               1       101348.88       1
1             2    15647311       Hill  ...               1       112542.58       0
2             3    15619304       Onio  ...               0       113931.57       1
3             4    15701354       Boni  ...               0        93826.63       0
4             5    15737888   Mitchell  ...               1        79084.10       0
...         ...         ...        ...  ...             ...             ...     ...
9995       9996    15606229   Obijiaku  ...               0        96270.64       0
9996       9997    15569892  Johnstone  ...               1       101699.77       0
9997       9998    15584532        Liu  ...               1        42085.58       1
9998       9999    15682355  Sabbatini  ...               0        92888.52       1
9999      10000    15628319     Walker  ...               0        38190.78       0

[10000 rows x 14 columns]

In [8]:
## Do preprocessing on column Geography using OneHotEncoding
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder()  # drop='
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [9]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [10]:
geo_encoder_df = pd.DataFrame(geo_encoder, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoder_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [14]:
data

      RowNumber  CustomerId  ... Geography_Germany  Geography_Spain
0             1    15634602  ...               0.0              0.0
1             2    15647311  ...               0.0              1.0
2             3    15619304  ...               0.0              0.0
3             4    15701354  ...               0.0              0.0
4             5    15737888  ...               0.0              1.0
...         ...         ...  ...               ...              ...
9995       9996    15606229  ...               0.0              0.0
9996       9997    15569892  ...               0.0              0.0
9997       9998    15584532  ...               0.0              0.0
9998       9999    15682355  ...               1.0              0.0
9999      10000    15628319  ...               0.0              0.0

[10000 rows x 19 columns]

In [17]:
data=data.drop(['Geography_France','Geography_Germany','Geography_Spain'],axis=1)
data

KeyError: "['Geography_France', 'Geography_Germany', 'Geography_Spain'] not found in axis"